# Site settings
title: "Podcast"
description: "LogChain Podcats"
podcast-description: "It's an amazing podcasts!"
url:  "https://logchainpodcast.netlify.app" # Actual base url of the website
baseurl: "/"                    # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
author:
  name: "Hüseyin Kaya"
  email: "kaya87826@gmail.com"
  url: "https://github.com/MoreThanKaya"
permalink: pretty
permalink: /:title
keywords: [podcast, jekyll]

#Plugins
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

#exclude: [_podcast.rss] #Ignore this, it will be used in case I decide to add rss feed

#Pagination
paginate: 5
paginate_path: "/page-:num/"

#Sass
sass:
  style: compressed
  sourcemap: never

#SEO
twitter:
  username: PandaSekh
  card: summary
facebook:
  app_id: 
logo: /assets/img/Podcast_Cover.png
social:
  name: Alessio Franceschi
  links:
    - https://github.com/MoreThanKaya
    - https://www.linkedin.com/in/MoreThanKaya
lang: it

#Podcast Metadata. Used by the RSS Feed, which currently isn't in use. So you can avoid this
podcast_title: LogChain Podcaster
podcast_author: LogChain
podcast_email: kaya87826gmail.com
podcast_subtitle: "Subtitle"
podcast_summary: "Summary"
podcast_description: "Description"
podcast_explicit: "no"
podcast_type: serial 
podcast_lang: en
podcast_launch: "2019-07-20" #Launch date of your podcast
podcast_copyright: "&#xA9;Hüseyin Kaya"
podcast_feed: 
podcast_artwork: "/assets/img/Podcast_Cover.png"
