analytics-id: 
#Pages
pages:
  - {name: 'Episodes', link: 'episodes.html'}
  - {name: 'Blog', link: 'https://logchainblog.netlify.app'}


social:
  - {icon: 'instagram', type: "brand", link: 'https://instagram.com/kayahuseyin7'}
  - {icon: 'envelope', type: "solid", link: 'mailto:kaya87826@gmail.com'}

websites-podcast:
  - {name: 'Apple Podcast', link: '#'}
  - {name: 'Spotify', link: '#'}
  - {name: 'YouTube', link: '#'}
  - {name: 'Android', link: '#'}
  - {name: 'Spreaker', link: '#'}
  - {name: 'Google Podcast', link: '#'}
  - {name: 'Anchor', link: '#'}
  - {name: 'Castbox', link: '#'}
  - {name: 'Overcast', link: '#'}
  - {name: 'RadioPublic', link: '#'}
  - {name: 'Breaker', link: '#'}  
  - {name: 'RSS', link: '#'}

translate-date: true #See _includes/date.html to translate the months' name
shownotes: true

#Disqus
disqus:
  disqus_shortname: 
